export {
  AVERAGE_CAR_ID,
  MAX_FREE_CARS,
  type FuelType,
  type DistanceUnit,
  type EfficiencyUnit,
  type Currency,
  type CarProfile,
  type UserSettings,
  type FuelPrices,
  type AppState,
  type PopupView,
  type CarQueryTrim,
  type TripRecord,
} from './types'
